export const SearchAllTabData = [
  {
    id: 1,
    title: 'Zeta Admin is a full featured,premium bootstrap admin template.',
    url: 'Zetaeducation.info/',
    detail: 'Zeta introduces a IELTS Coaching, TOEFL Coaching, GRE Coaching, GMAT Coaching, SAT Coaching in Surat.',
    star: '2.5 stars',
    vote: '590 votes',
    news: 'Music',
    videoLink: 'https://www.youtube.com/embed/CJnfAXlBRTE',
  },
  {
    id: 2,
    title: 'Cuba Admin is a full featured,premium bootstrap admin template.',
    url: 'Cubaeducation.info/',
    detail: 'Cuba introduces a IELTS Coaching, TOEFL Coaching, GRE Coaching, GMAT Coaching, SAT Coaching in Surat.',
    star: '2.5 stars',
    vote: '590 votes',
    news: 'Music',
    videoLink: 'https://www.youtube.com/embed/tRjG45ut8gU',
  },
  {
    id: 3,
    title: 'Koho Admin Dashboard Template.',
    url: 'Kohoeducation.info/',
    detail: 'Koho introduces a IELTS Coaching, TOEFL Coaching, GRE Coaching, GMAT Coaching, SAT Coaching in Surat.',
    star: '2.5 stars',
    vote: '590 votes',
    news: 'Music',
    videoLink: 'https://www.youtube.com/embed/-L4gEk7cOfk',
  },
  {
    id: 4,
    title: 'Viho Admin is a full featured,premium bootstrap admin template.',
    url: 'Vihoeducation.info/',
    detail: 'Viho introduces a IELTS Coaching, TOEFL Coaching, GRE Coaching, GMAT Coaching, SAT Coaching in Surat.',
    star: '2.5 stars',
    vote: '590 votes',
    news: 'Music',
    videoLink: 'https://www.youtube.com/embed/wpmHZspl4EM',
  },
  {
    id: 5,
    title: 'Tivo Admin is a full featured,premium bootstrap admin template',
    url: 'Tivoeducation.info/',
    detail: 'Tivo introduces a IELTS Coaching, TOEFL Coaching, GRE Coaching, GMAT Coaching, SAT Coaching in Surat.',
    star: '2.5 stars',
    vote: '590 votes',
    news: 'Music',
    videoLink: 'https://www.youtube.com/embed/-L4gEk7cOfk',
  },
];
